#!/usr/bin/zsh
cp -r ~/.vim/** ~/Documents/GitHub/dotfiles/.vim
cp -r ~/.local/share/konsole ~/Documents/GitHub/dotfiles/.local/share/
cp ~/.config/nvim/init.vim ~/Documents/GitHub/dotfiles/.config/nvim/init.vim
cp ~/.zshrc ~/Documents/GitHub/dotfiles/.zshrc

# backup&restore
cp ~/backup ~/Documents/GitHub/dotfiles/backup
cp ~/restore ~/Documents/GitHub/dotfiles/restore

