#!/usr/bin/zsh
mkdir ~/restore-files
rsync -a ~/Documents/GitHub/dotfiles ~/restore-files/
mv ~/restore-files/dotfiles/** ~/
rm -rf ~/restore-files
echo "Restored the backup from GitHub(oezguerisbert/dotfiles)"


